import { MigrationInterface, QueryRunner } from "typeorm";

export class IntializeWithAllTables1778847040611 implements MigrationInterface {
    name = 'IntializeWithAllTables1778847040611'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "UQ_881f72bac969d9a00a1a29e1079" UNIQUE ("slug"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salons_images" ("id" SERIAL NOT NULL, "image_url" character varying(500) NOT NULL, "is_primary" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "salon_id" integer, CONSTRAINT "PK_de783c2328f561600b877ee1f1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salon_bank_details" ("id" SERIAL NOT NULL, "account_holder_name" character varying(255) NOT NULL, "account_number" bigint NOT NULL, "ifsc_code" character varying(20) NOT NULL, "bank_name" character varying(255) NOT NULL, "upi_id" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "salon_id" integer, CONSTRAINT "PK_3c39ce019e13e11c32e364dd6eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salon_availability" ("id" SERIAL NOT NULL, "day_of_week" character varying(20) NOT NULL, "start_time" TIME, "end_time" TIME, "is_closed" boolean NOT NULL DEFAULT false, "capacity" integer NOT NULL DEFAULT '1', "salon_id" integer, CONSTRAINT "PK_296aa8598223ddb90b80e96231a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_categories" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7ef2e28b495d09a4eb28997c653" UNIQUE ("name"), CONSTRAINT "PK_fe4da5476c4ffe5aa2d3524ae68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salon_services" ("id" SERIAL NOT NULL, "price" integer NOT NULL, "duration" integer NOT NULL, "status" boolean NOT NULL DEFAULT true, "salon_id" integer, "service_id" integer, CONSTRAINT "PK_3b5fc6c40f202bbc32640e37e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."services_master_gender_type_enum" AS ENUM('male', 'female', 'unisex')`);
        await queryRunner.query(`CREATE TABLE "services_master" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "image" character varying(500), "gender_type" "public"."services_master_gender_type_enum" NOT NULL DEFAULT 'unisex', "default_duration" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category_id" integer, CONSTRAINT "PK_e29895fa6d73dff35b55bd28c96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "barber_services" ("id" SERIAL NOT NULL, "barber_id" integer, "service_id" integer, CONSTRAINT "UQ_1c13e7755814fe409603c84d985" UNIQUE ("barber_id", "service_id"), CONSTRAINT "PK_19537fd8429d9ef1c761a8c0cf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "booking_services" ("id" SERIAL NOT NULL, "price" numeric(10,2) NOT NULL, "duration" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "booking_id" integer, "service_id" integer, CONSTRAINT "PK_8997bf4d0728c8740c87694d59a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "booking_slots" ("id" SERIAL NOT NULL, "slot_date" date NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "booking_id" integer, "salon_id" integer, CONSTRAINT "PK_9596369395c8747c94a5606c4de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."settlements_status_enum" AS ENUM('pending', 'processed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "settlements" ("id" SERIAL NOT NULL, "total_amount" numeric(10,2) NOT NULL, "commission" numeric(10,2) NOT NULL DEFAULT '0', "net_amount" numeric(10,2) NOT NULL, "status" "public"."settlements_status_enum" NOT NULL DEFAULT 'pending', "settlement_date" date NOT NULL, "processed_at" TIMESTAMP, "payment_method" character varying(100), "payout_reference" character varying(255), "start_date" date NOT NULL, "end_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "salon_id" integer, CONSTRAINT "PK_5f523ce152b84e818bff9467aab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_gateway_logs" ("id" SERIAL NOT NULL, "gateway_name" character varying(100) NOT NULL, "gateway_payment_id" character varying(255), "gateway_order_id" character varying(255), "gateway_signature" character varying(500), "raw_response" text, "status" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "payment_id" integer, CONSTRAINT "PK_22da83fe8cefab76c4fa4208cea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'paid', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_transaction_status_enum" AS ENUM('pending', 'paid', 'failed')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" SERIAL NOT NULL, "amount" numeric(10,2) NOT NULL, "commission" numeric(10,2) NOT NULL DEFAULT '0', "net_amount" numeric(10,2) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "payment_method" character varying(100), "transaction_ref" character varying(255), "transaction_status" "public"."payments_transaction_status_enum" NOT NULL DEFAULT 'pending', "paid_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "booking_id" integer, "settlement_id" integer, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'confirmed', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" SERIAL NOT NULL, "total_price" numeric(10,2) NOT NULL, "total_duration" integer NOT NULL, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'pending', "cancelled_at" TIMESTAMP, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "customer_id" integer, "salon_id" integer, "preferred_barber_id" integer, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."barbers_status_enum" AS ENUM('active', 'inactive', 'on_leave')`);
        await queryRunner.query(`CREATE TABLE "barbers" ("id" SERIAL NOT NULL, "specialization" character varying(255), "status" "public"."barbers_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, "salon_id" integer, CONSTRAINT "PK_3602c05627856e4cd6d91585d65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blocked_slots" ("id" SERIAL NOT NULL, "date" date NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "salon_id" integer, CONSTRAINT "PK_695a263308f46c2fb48fec80fb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "slot_locks" ("id" SERIAL NOT NULL, "slot_date" date NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "locked_until" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "salon_id" integer, "customer_id" integer, CONSTRAINT "PK_f8791e2657d6720dcb5baeb89b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "review_images" ("id" SERIAL NOT NULL, "image_url" character varying(500) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "review_id" integer, CONSTRAINT "PK_dfb8fbc1b0534f20de489a64358" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" SERIAL NOT NULL, "rating" integer NOT NULL, "comment" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "customer_id" integer, "salon_id" integer, CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."salons_salon_type_enum" AS ENUM('male', 'female', 'unisex')`);
        await queryRunner.query(`CREATE TYPE "public"."salons_status_enum" AS ENUM('active', 'inactive', 'pending', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "salons" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "salon_type" "public"."salons_salon_type_enum" NOT NULL, "status" "public"."salons_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "owner_id" integer, "address_id" integer, CONSTRAINT "PK_4cbe0adde860abd3b68b196a0b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" SERIAL NOT NULL, "line1" character varying(255) NOT NULL, "line2" character varying(255), "area" character varying(150) NOT NULL, "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "country" character varying(100) NOT NULL DEFAULT 'India', "pincode" character varying(10) NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('booking', 'payment', 'reminder')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "message" text, "reference_id" integer, "reference_type" character varying(100), "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TYPE "public"."users_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "contact1" character varying(20) NOT NULL, "contact2" character varying(20), "gender" "public"."users_gender_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "role_id" integer, "address_id" integer, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" SERIAL NOT NULL, "key" character varying(150) NOT NULL, "value" text NOT NULL, "description" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key"), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "salons_images" ADD CONSTRAINT "FK_e2d39583cec9b3dc255f22238c9" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salon_bank_details" ADD CONSTRAINT "FK_e19f7e81d9d62aaf96b03c4b4c2" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salon_availability" ADD CONSTRAINT "FK_0d246f7109c637d28610876e55e" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salon_services" ADD CONSTRAINT "FK_2a594c739b53c9066b9d6757059" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salon_services" ADD CONSTRAINT "FK_d7924d20be498c5a43808d7e0dc" FOREIGN KEY ("service_id") REFERENCES "services_master"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services_master" ADD CONSTRAINT "FK_ebd86464a71bf714d46bfe90ad0" FOREIGN KEY ("category_id") REFERENCES "service_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barber_services" ADD CONSTRAINT "FK_e70bcc147df17357820e5e9d69f" FOREIGN KEY ("barber_id") REFERENCES "barbers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barber_services" ADD CONSTRAINT "FK_8b55a829bc87a2406fb3df3d769" FOREIGN KEY ("service_id") REFERENCES "services_master"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_813fb23d7e327b6d9cff929cce6" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_6e853453a3c24df1beed35c13eb" FOREIGN KEY ("service_id") REFERENCES "services_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_slots" ADD CONSTRAINT "FK_2412aee53f210614ab4d37cbcd9" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_slots" ADD CONSTRAINT "FK_e24c0dc38d57dffdcf58f0eb553" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlements" ADD CONSTRAINT "FK_18a6243105b68fa502867f6b13f" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_gateway_logs" ADD CONSTRAINT "FK_8182e9418a24320f483d0d8faf0" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_33d682c376b9b8b29fca170c8ca" FOREIGN KEY ("settlement_id") REFERENCES "settlements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_f53f5edf6bce876f575fca51d2e" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_0272520d94ab78494d4f6c665c6" FOREIGN KEY ("preferred_barber_id") REFERENCES "barbers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barbers" ADD CONSTRAINT "FK_51d5f4523f06d92e18da7d97506" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barbers" ADD CONSTRAINT "FK_72b225358c061166593845b6b73" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocked_slots" ADD CONSTRAINT "FK_9beb50c215cfbfe742f4f2992cd" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slot_locks" ADD CONSTRAINT "FK_9c198eb28f78c4f789fb95d372f" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slot_locks" ADD CONSTRAINT "FK_2aea05dae34127f6def1c2770c0" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD CONSTRAINT "FK_45b8671ec9f03b6682a52adb120" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_0b8611bcfb1e08045362b1e42e6" FOREIGN KEY ("salon_id") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salons" ADD CONSTRAINT "FK_b11fe93002605ce1eb760de43a7" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salons" ADD CONSTRAINT "FK_d3aa39cda9976b848a4f8f4ad9a" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1b05689f6b6456680d538c3d2ea" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1b05689f6b6456680d538c3d2ea"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP CONSTRAINT "FK_d3aa39cda9976b848a4f8f4ad9a"`);
        await queryRunner.query(`ALTER TABLE "salons" DROP CONSTRAINT "FK_b11fe93002605ce1eb760de43a7"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_0b8611bcfb1e08045362b1e42e6"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b"`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP CONSTRAINT "FK_45b8671ec9f03b6682a52adb120"`);
        await queryRunner.query(`ALTER TABLE "slot_locks" DROP CONSTRAINT "FK_2aea05dae34127f6def1c2770c0"`);
        await queryRunner.query(`ALTER TABLE "slot_locks" DROP CONSTRAINT "FK_9c198eb28f78c4f789fb95d372f"`);
        await queryRunner.query(`ALTER TABLE "blocked_slots" DROP CONSTRAINT "FK_9beb50c215cfbfe742f4f2992cd"`);
        await queryRunner.query(`ALTER TABLE "barbers" DROP CONSTRAINT "FK_72b225358c061166593845b6b73"`);
        await queryRunner.query(`ALTER TABLE "barbers" DROP CONSTRAINT "FK_51d5f4523f06d92e18da7d97506"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_0272520d94ab78494d4f6c665c6"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_f53f5edf6bce876f575fca51d2e"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_33d682c376b9b8b29fca170c8ca"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2"`);
        await queryRunner.query(`ALTER TABLE "payment_gateway_logs" DROP CONSTRAINT "FK_8182e9418a24320f483d0d8faf0"`);
        await queryRunner.query(`ALTER TABLE "settlements" DROP CONSTRAINT "FK_18a6243105b68fa502867f6b13f"`);
        await queryRunner.query(`ALTER TABLE "booking_slots" DROP CONSTRAINT "FK_e24c0dc38d57dffdcf58f0eb553"`);
        await queryRunner.query(`ALTER TABLE "booking_slots" DROP CONSTRAINT "FK_2412aee53f210614ab4d37cbcd9"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_6e853453a3c24df1beed35c13eb"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_813fb23d7e327b6d9cff929cce6"`);
        await queryRunner.query(`ALTER TABLE "barber_services" DROP CONSTRAINT "FK_8b55a829bc87a2406fb3df3d769"`);
        await queryRunner.query(`ALTER TABLE "barber_services" DROP CONSTRAINT "FK_e70bcc147df17357820e5e9d69f"`);
        await queryRunner.query(`ALTER TABLE "services_master" DROP CONSTRAINT "FK_ebd86464a71bf714d46bfe90ad0"`);
        await queryRunner.query(`ALTER TABLE "salon_services" DROP CONSTRAINT "FK_d7924d20be498c5a43808d7e0dc"`);
        await queryRunner.query(`ALTER TABLE "salon_services" DROP CONSTRAINT "FK_2a594c739b53c9066b9d6757059"`);
        await queryRunner.query(`ALTER TABLE "salon_availability" DROP CONSTRAINT "FK_0d246f7109c637d28610876e55e"`);
        await queryRunner.query(`ALTER TABLE "salon_bank_details" DROP CONSTRAINT "FK_e19f7e81d9d62aaf96b03c4b4c2"`);
        await queryRunner.query(`ALTER TABLE "salons_images" DROP CONSTRAINT "FK_e2d39583cec9b3dc255f22238c9"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TABLE "salons"`);
        await queryRunner.query(`DROP TYPE "public"."salons_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."salons_salon_type_enum"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "review_images"`);
        await queryRunner.query(`DROP TABLE "slot_locks"`);
        await queryRunner.query(`DROP TABLE "blocked_slots"`);
        await queryRunner.query(`DROP TABLE "barbers"`);
        await queryRunner.query(`DROP TYPE "public"."barbers_status_enum"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_transaction_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "payment_gateway_logs"`);
        await queryRunner.query(`DROP TABLE "settlements"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_status_enum"`);
        await queryRunner.query(`DROP TABLE "booking_slots"`);
        await queryRunner.query(`DROP TABLE "booking_services"`);
        await queryRunner.query(`DROP TABLE "barber_services"`);
        await queryRunner.query(`DROP TABLE "services_master"`);
        await queryRunner.query(`DROP TYPE "public"."services_master_gender_type_enum"`);
        await queryRunner.query(`DROP TABLE "salon_services"`);
        await queryRunner.query(`DROP TABLE "service_categories"`);
        await queryRunner.query(`DROP TABLE "salon_availability"`);
        await queryRunner.query(`DROP TABLE "salon_bank_details"`);
        await queryRunner.query(`DROP TABLE "salons_images"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
